import type { Tech, TechId } from "../types/tech.js";

export const CATALOG: Record<TechId, Tech> = {
  nextjs: {
    id: "nextjs",
    category: "framework",
    name: "Next.js",
    role: "The Godfather",
    description: "App Router, React 19, Server Components",
    requires: [],
    conflictsWith: [],
    provides: ["tailwindcss"],
    packages: ["next"],
    minNode: ">=20.9.0",
  },
  tailwindcss: {
    id: "tailwindcss",
    category: "styling",
    name: "Tailwind CSS",
    role: "The Designer",
    description: "Utility-first styling",
    requires: [],
    conflictsWith: [],
    provides: [],
    packages: ["tailwindcss"],
    minNode: ">=20.9.0",
  },
  shadcn: {
    id: "shadcn",
    category: "ui",
    name: "shadcn/ui",
    role: "The Tailor",
    description: "Beautiful components with Radix UI",
    requires: ["tailwindcss"],
    conflictsWith: [],
    provides: [],
    packages: [],
    minNode: ">=20.9.0",
  },
  drizzle: {
    id: "drizzle",
    category: "database",
    name: "Drizzle ORM",
    role: "The Accountant",
    description: "Type-safe database operations",
    requires: [],
    conflictsWith: [],
    provides: [],
    packages: ["drizzle-orm", "@libsql/client"],
    minNode: ">=20.9.0",
  },
  "vercel-ai-sdk": {
    id: "vercel-ai-sdk",
    category: "ai",
    name: "Vercel AI SDK",
    role: "The Consultant",
    description: "AI applications with function calling",
    requires: [],
    conflictsWith: [],
    provides: [],
    packages: ["ai", "@ai-sdk/react"],
    minNode: ">=20.9.0",
  },
  "memory-mcp-server": {
    id: "memory-mcp-server",
    category: "mcp",
    name: "Memory MCP Server",
    role: "The Archivist",
    description: "Persistent knowledge-graph memory for Claude Code / MCP clients",
    requires: [],
    conflictsWith: [],
    provides: [],
    packages: [],
    minNode: ">=20.9.0",
  },
};
